# Generated by Django 4.1.3 on 2022-11-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datos_Familiares',
        ),
        migrations.DeleteModel(
            name='Sobrino',
        ),
        migrations.DeleteModel(
            name='Tio',
        ),
    ]
