# Generated by Django 4.1.2 on 2022-11-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_delete_datos_familiares_delete_sobrino_delete_tio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Primo',
            new_name='Familia',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='documento',
            new_name='edad',
        ),
    ]
