# Generated by Django 4.1.3 on 2022-11-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0004_equipo_jugador_manager_delete_familia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='nacimiento',
        ),
        migrations.AddField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
