# Generated by Django 4.1.3 on 2022-11-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0005_remove_jugador_nacimiento_jugador_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(max_length=40),
        ),
    ]
